require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '13.0'
use_frameworks!

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCamera', :path => '../../node_modules/@capacitor/camera'
  pod 'CapacitorGeolocation', :path => '../../node_modules/@capacitor/geolocation'
end

target 'App' do
  capacitor_pods
end

post_install do |installer|
  assertDeploymentTarget(installer)
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # Add these specific header search paths
      config.build_settings['HEADER_SEARCH_PATHS'] = [
        '$(inherited)',
        '${PODS_ROOT}/../../node_modules/@capacitor/ios/Capacitor/Capacitor/Bridge',
        '${PODS_ROOT}/../../node_modules/@capacitor/ios/CapacitorCordova'
      ]
    end
  end
end